#= Install Ruadan Requirements ==============================
# Update and Install Ruadan
[Install or Update]
Command: apt update && apt -yq install git nmap nfs-common exploitdb nbtscan enum4linux smbclient onesixtyone sslscan sslyze cisco-torch dnsrecon nikto dirb gobuster whatweb wafw00f wpscan cewl curl ident-user-enum hydra rdesktop smtp-user-enum
[GIT Ruadan to Python Site Package]
Command: git clone https://github.com/overcyber/ruadan.git /opt/ruadan
[Clean up previous install]
Command: rm /usr/local/bin/ruadan
[Install Ruadan Python Package]
Command: python3 /opt/ruadan/setup.py install
[Create Ruadan Executable in usr local bin]
Command: printf '#!/usr/bin/env python3\nimport sys, os\nimport Ruadan2\nRuadan2.main()\n' > /usr/local/bin/ruadan
[Add execute permission to Ruadan]
Command: chmod +x /usr/local/bin/ruadan

# Install Vulscan
[Clone Vulscan]
Command: git clone https://github.com/scipag/vulscan /usr/share/nmap/scripts/vulscan
[Update Vulscan Sources]
Command: /usr/share/nmap/scripts/vulscan/updateFiles.sh
[Update WPScan]
Command: wpscan --update

#= Service Ports ==============================
# The following services will be associated with port numbers in cases where services cannot be identified by Nmap
[Service Ports]
always: 0

#Ruadan config file
#= System Configuration ==============================
[System]
Debug: 0
Verbose: 0
